/*
 * This file is automatic generated by automatic-i18n.
 * You can only change variable's property and value.
 * Others will be clear after rerun automatic-i18n program.
 */
import { LocalKey } from './types';

const locale: Record<LocalKey, string> = {
  key0002: '张成思',
  key0005: '箭头函数组件字符串提取',
  key0006: '箭头函数组件{v1}jsx',
  key0008: '函数组件字符串提取',
  key0009: '函数组件{v1}jsx',
};

export default locale;
