/*
 * This file is automatic generated by automatic-i18n.
 * You can only change variable's property and value.
 * Others will be clear after rerun automatic-i18n program.
 */
import { LocalKey } from './types';

const locale: Record<LocalKey, string> = {
  key199c71859__: 'Welcome back, user!',
  key1eb72f170__: 'a+b',
  key1ef3e3d1c__: '{v1} Click me {v2} {v3} {v4}',
  key1fa68539e__: 'Action title',
};

export default locale;
