import { program, Option } from 'commander';
import I18nReplacer, {
  defaultTargets,
  defaultDistLocaleDir,
  defaultLocaleToReplace,
  defaultLocalesToGenerate,
} from '..';
import { availableLocales } from '../types';
import pkg from '../../package.json';
import resolveMergeConflict from '../resolveMergeConflict';

export async function cli() {
  program
    .option(
      `-t --targets <fileOrDir...>`,
      `directories or files to extract locales, default is [${defaultTargets()}]`
    )
    .option(
      `-d --distLocaleDir <fileOrDir>`,
      `folder where message files are generated, default is [${defaultDistLocaleDir()}]`
    )
    .addOption(
      new Option(
        `-sl --localeToReplace <fileOrDir>`,
        `locale to search in source code, default is [${defaultLocaleToReplace}]`
      ).choices(availableLocales)
    )
    .addOption(
      new Option(
        `-tl --localesToGenerate <locales...>`,
        `locales to generate, default is [${defaultLocalesToGenerate.join(
          ','
        )}] you can input multiple locales with space ex: [-tl en-us zh-cn]`
      ).choices(availableLocales)
    )
    .option(
      '-g, --global',
      'if prefer global intl obj instead hook, default is [false]'
    )
    .option(
      '-e, --excludes <filesOrDirs...>',
      'files or dirs to excludes, default is [node_modules, file or dir start with .]'
    )
    .option('-db, --debug', 'if show extra message, default is [false]')
    .option(
      '-m, --meaningKey',
      'change the key to the English abbreviation if en-us has a translation.Default is [false]'
    )
    .option(
      '-u, --uniqIntlKey',
      'if message key generated by hash message to prevent key conflict, default is [false]'
    )
    .option('-v, --version', 'show npm version');

  // 新增 merge 子命令
  program
    .command('merge [distDir] [outputDir]')
    .description(
      'resolve git merge conflicts in locale directory; optionally write merged result to outputDir'
    )
    .action(
      async (distDir: string | undefined, outputDir: string | undefined) => {
        const targetDir = distDir || defaultDistLocaleDir();
        const outDir = outputDir || targetDir;
        try {
          await resolveMergeConflict(targetDir, outDir);
          console.log(
            `[merge] resolved conflicts in: ${targetDir} -> written to: ${outDir}`
          );
        } catch (e: any) {
          console.error('[merge] failed: ' + (e?.message || e));
          process.exitCode = 1;
        }
      }
    );

  // 主命令行为（无子命令时执行原逻辑）
  program.action(async () => {
    const opts = program.opts();
    if (opts.version) {
      console.log('v' + pkg.version);
      return;
    }
    await I18nReplacer.createI18nReplacer(opts).replace();
  });

  await program.parseAsync();
}
