/*
 * This file is automatic generated by fast-i18n.
 * You can only change variable's property and value.
 * Others will be clear after rerun fast-i18n program.
 */
import { LocalKey } from './types';

const locale: Record<LocalKey, string> = {
  key0001: 'English',
  key0002: 'Chinese',
  key0003: '{v1} and {v2}',
  key0004: 'Please choose your locale from: {v1} {v2}',
};

export default locale;
