/*
 * This file is automatic generated by automatic-i18n.
 * You can only change variable's property and value.
 * Others will be clear after rerun automatic-i18n program.
 */
import { LocalKey } from './types';

const locale: Record<LocalKey, string> = {
  key0001: '{v1} and {v2}',
  key0002: 'Please choose your locale from: {v1} {v2}',
};

export default locale;
