/*
 * This file is automatic generated by automatic-i18n.
 * You can only change variable's property and value.
 * Others will be clear after rerun automatic-i18n program.
 */
import { LocalKey } from './types';

const locale: Record<LocalKey, string> = {
  key0001: '王五',
  key0003: '男',
  key0004: '孙六',
  key0005: '孙孙',
  key0007: '好的',
  key0008: '不好',
  key0009: '  sffds你好{v1}哈哈{v2}为什么',
  key0010: '{v1}北京大学',
  key0011: '真是男的',
  key0012: '你好{v1}哈哈',
  key0013: '北京{v1}大学',
  key0014: '套娃1{v1}套娃2',
  key0015: '套娃3',
  key0016: '北京大学{v1}真不错aaaa{v1}哈哈{v2}',
  key0017: '租户不存在',
  key0018: '请重新登录，或联系系统管理员创建至少一个租户',
  key0019: '知道了',
  key0020: '和`',
  key0021: ' sfdsfds你好dsffds你好',
  key0022: '别名',
  key0023: '别名2',
  key0024: '你好',
  key0025: '意义咋样 {v1} : sffdsfd',
  key0026: '请输入',
  key0027: '你好{v1}哈哈{v2}为什么',
  key0028: '哈哈{v1}你好',
  key0029: 'fff空节点zzx空节点',
  key0030: '空节点',
  key0031: '`${v1}html中纯文本`',
  key0032: '然后分割\n      {v1}然后分割',
};

export default locale;
