/*
 * This file is automatic generated by automatic-i18n.
 * You can only change variable's property and value.
 * Others will be clear after rerun automatic-i18n program.
 */
import { LocalKey } from './types';

const locale: Record<LocalKey, string> = {
  key11e39f792__: 'excel',
  key13b999b27__: 'hello sir!',
  key1b2e24430__: 'lucy',
  key1eaa0f157__: 'hello {v1}',
};

export default locale;
