/*
 * This file is automatic generated by automatic-i18n.
 * You can only change variable's property and value.
 * Others will be clear after rerun automatic-i18n program.
 */
import { LocalKey } from "./types";

const locale: Record<LocalKey, string> = {
  key0001: "你好",
  key0002: "再见",
};

export default locale;
