/*
 * This file is automatic generated by fast-i18n.
 * You can only change variable's property and value.
 * Others will be clear after rerun fast-i18n program.
 */
import { LocalKey } from './types';

const locale: Record<LocalKey, string> = {
  goodbye: 'oldGoodBye',
  goodbye_1: 'goodbye',
  hellosdffdsfds: 'hello!_sdffdsfds',
  key0001: '哈哈哈',
  key0002: '哈\\n  哈',
  key0003: "'哈哈哈",
  key0004: '你好{v1}',
  thatIsSoGoodILoveYouVeryMuchGo_:
    'that is so good, i love you very much, goodbye mr schneider',
  yoursIsXxx: "your's is xxx",
};

export default locale;
