/*
 * This file is automatic generated by automatic-i18n.
 * You can only change variable's property and value.
 * Others will be clear after rerun automatic-i18n program.
 */
import { LocalKey } from './types';

const locale: Record<LocalKey, string> = {
  goodbye_1: 'goodbye',
  hellosdffdsfds: 'hello!_sdffdsfds',
  key0005: '你好{v1}',
  thatIsSoGoodILoveYouVeryMuchGo_:
    'that is so good, i love you very much, goodbye mr schneider',
  yoursIsXxx: "your's is xxx",
  key0001: '哈哈哈',
  key0002:
    '哈\
  哈',
  goodbye: 'oldGoodBye',
  key0003: "'哈哈哈",
  key0004:
    '哈哈\
  哈哈',
};

export default locale;
