/*
 * This file is automatic generated by automatic-i18n.
 * You can only change variable's property and value.
 * Others will be clear after rerun automatic-i18n program.
 */
import { LocalKey } from './types';

const locale: Record<LocalKey, string> = {
  goodbye_1: '再见',
  hellosdffdsfds: '你好',
  key0005: '你好{v1}',
  thatIsSoGoodILoveYouVeryMuchGo_: '师德师风佛挡杀佛佛挡杀佛水电费水电费',
  yoursIsXxx: 'ssss',
  key0001: '哈哈哈',
  key0002:
    '哈\
  哈',
  goodbye: '老再见',
  key0003: "'哈哈哈",
  key0004:
    '哈哈\
  哈哈',
};

export default locale;
