/*
 * This file is automatic generated by automatic-i18n.
 * You can only change variable's property and value.
 * Others will be clear after rerun automatic-i18n program.
 */
import { LocalKey } from './types';

const locale: Record<LocalKey, string> = {
<<<<<<< HEAD
  key12efc0368__: 'Enter step size data',
  key14abf6103__: 'Enter step size data one by one',
=======
  key14abf6103__: 'Enter step size data one by one',
  key1522cc8c2__: 'Each step size data ({v1})',
  key11b8cf7b6__:
    'Please ensure all sites and AuM are debugged before formal authorization',
  key12efc0368__: 'Enter step size data',

>>>>>>> feature/20971-authority
  key1b92d81b6__: 'Create up to 30 groups',
<<<<<<< HEAD
  shanghai: 'Enter step size data',
=======
  'key1+bQ2F+jYnnfnpnZppa7cug__': 'Enter step size data',
  'beijing': 'beijing'
>>>>>>> feature/20971-authority
};

export default locale;
