/*
 * This file is automatic generated by automatic-i18n.
 * You can only change variable's property and value.
 * Others will be clear after rerun automatic-i18n program.
 */
import { LocalKey } from './types';

const locale: Record<LocalKey, string> = {
<<<<<<< HEAD

key12efc0368__: '输入步长数据',

key14abf6103__: '逐个输入步长数据',

key1522cc8c2__: '每个步长数据 ({v1})',

=======

key14abf6103__: '逐个输入步长数据',

key1522cc8c2__: '每个步长数据 ({v1})',

key11b8cf7b6__:

'请确保所有站点和 AuM 在正式授权前都已调试',

key12efc0368__: '输入步长数据',

>>>>>>> feature/20971-authority

key1b92d81b6__: '最多创建 30 个groups',

<<<<<<< HEAD

shanghai: '上海',


=======

beijing: '北京',
'key1+bQ2F+jYnnfnpnZppa7cug__': 'sdffds',

>>>>>>> feature/20971-authority
};

export default locale;
