/*
 * This file is automatic generated by fast-i18n.
 * You can only change variable's property and value.
 * Others will be clear after rerun fast-i18n program.
 */
import { LocalKey } from './types';

const locale: Record<LocalKey, string> = {
  key0001: '里面{v1}',
  key0002: '你好',
  key0003: '不好',
  key0004: 'fsffdsfd{v1}你好呀{v2}哈哈{v3}ffff{v4}{v5}xz{v2}',
  key0005: '张三',
  key0006: 's张三dsf',
};

export default locale;
