/*
 * This file is automatic generated by automatic-i18n.
 * You can only change variable's property and value.
 * Others will be clear after rerun automatic-i18n program.
 */
import { LocalKey } from './types';

const locale: Record<LocalKey, string> = {
  key0001: '7月1日',
  key0002: '7月5日',
  key0003: '7月6日',
  key0004: '7月8日',
  key0005: '忽略',
};

export default locale;
