/*
 * This file is automatic generated by fast-i18n.
 * You can only change variable's property and value.
 * Others will be clear after rerun fast-i18n program.
 */
import { LocalKey } from './types';

const locale: Record<LocalKey, string> = {
  key0001: 'hello!_sdffdsfds',
  key0002: 'goodbye',
  goodbye: 'oldGoodBye',
  key0003: 'that is so good, i love you very much, goodbye mr schneider',
  key0004: "your's is xxx",
};

export default locale;
