/*
 * This file is automatic generated by fast-i18n.
 * You can only change variable's property and value.
 * Others will be clear after rerun fast-i18n program.
 */
import { LocalKey } from './types';

const locale: Record<LocalKey, string> = {
  key0001: '你好',
  key0002: '再见',
  goodbye: '老再见',
  key0003: '师德师风佛挡杀佛佛挡杀佛水电费水电费',
  key0004: 'ssss',
};

export default locale;
