/*
 * This file is automatic generated by automatic-i18n.
 * You can only change variable's property and value.
 * Others will be clear after rerun automatic-i18n program.
 */
import { LocalKey } from './types';

const locale: Record<LocalKey, string> = {
  key0001: '哈哈{v1}你好',
  key0002: '你好',
  key0003: 'sd你好fs',
  key0004: '哈哈',
  key0005: '哈哈{v1}',
  key0006: '你好{v1}',
  key0007: '准备{v1}再见{v1}',
  key0008: '再见',
  key0009: '张成思',
};

export default locale;
